name: pre-commit

on: push
#  release:
#    types:
#      - created


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: install build dependencies
        run: pip install .[build]
      - name: build
        run: hatch build
      - name: Store package distributions
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish
    #    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      #      name: pypi
      #      url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name
      name: testpypi
      url: https://test.pypi.org/p/ttl-dict
